# Generated by Django 5.2.8 on 2026-01-06 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('content', models.TextField(blank=True)),
                ('content_html', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published', models.BooleanField(default=False)),
                ('featured_image', models.TextField(blank=True, help_text='Featured image URL or data URI for post cards')),
                ('excerpt', models.TextField(blank=True, help_text='Short excerpt for previews', max_length=300)),
                ('meta_title', models.CharField(blank=True, help_text='SEO title (max 60-70 chars)', max_length=70)),
                ('meta_description', models.CharField(blank=True, help_text='SEO description (max 155-160 chars)', max_length=160)),
                ('og_image', models.TextField(blank=True, help_text='Open Graph image URL or data URI for social sharing')),
            ],
        ),
        migrations.CreateModel(
            name='LiveQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=10, unique=True)),
                ('price', models.DecimalField(decimal_places=4, max_digits=15)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['ticker'],
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('live_quotes_enabled', models.BooleanField(default=False, help_text='Enable automatic live quote updates during market hours')),
                ('live_quotes_interval', models.IntegerField(choices=[(5, '5 minutes'), (15, '15 minutes'), (30, '30 minutes'), (60, '1 hour')], default=15, help_text='How often to update live quotes (minutes)')),
                ('last_quote_update', models.DateTimeField(blank=True, help_text='Last time quotes were updated', null=True)),
                ('last_update_count', models.IntegerField(default=0, help_text='Number of tickers updated in last update')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='DividendHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=10)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
            options={
                'ordering': ['ticker', 'date'],
                'indexes': [models.Index(fields=['ticker', 'date'], name='core_divide_ticker_309470_idx')],
                'unique_together': {('ticker', 'date')},
            },
        ),
        migrations.CreateModel(
            name='MarketDataCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('close_price', models.DecimalField(decimal_places=4, max_digits=15)),
                ('dividend', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['ticker', 'date'], name='core_market_ticker_6b14c6_idx')],
                'unique_together': {('ticker', 'date')},
            },
        ),
        migrations.CreateModel(
            name='CashTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('type', models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal')], max_length=10)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_transactions', to='core.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=10)),
                ('date', models.DateField()),
                ('close_price', models.DecimalField(decimal_places=4, max_digits=15)),
            ],
            options={
                'ordering': ['ticker', 'date'],
                'indexes': [models.Index(fields=['ticker', 'date'], name='core_priceh_ticker_489f06_idx')],
                'unique_together': {('ticker', 'date')},
            },
        ),
        migrations.CreateModel(
            name='SEOReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('model', models.CharField(default='gemini-2.5-flash', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seo_reports', to='core.blogpost')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('date', models.DateTimeField()),
                ('side', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=15)),
                ('price', models.DecimalField(decimal_places=4, max_digits=15)),
                ('fees', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='core.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='DailySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_units', models.DecimalField(decimal_places=6, max_digits=15)),
                ('nav', models.DecimalField(decimal_places=4, max_digits=15)),
                ('cash_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_snapshots', to='core.portfolio')),
            ],
            options={
                'ordering': ['date'],
                'indexes': [models.Index(fields=['portfolio', 'date'], name='core_dailys_portfol_1c9e69_idx')],
                'unique_together': {('portfolio', 'date')},
            },
        ),
        migrations.CreateModel(
            name='DailyPortfolioValuation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('cash_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('market_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('daily_return', models.DecimalField(decimal_places=6, max_digits=10)),
                ('daily_dividend', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('external_cash_flow', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_valuations', to='core.portfolio')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['portfolio', 'date'], name='core_dailyp_portfol_e1882c_idx')],
                'unique_together': {('portfolio', 'date')},
            },
        ),
        migrations.CreateModel(
            name='PortfolioDailyValueV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cash_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('invested_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_dividends', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_deposits', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_withdrawals', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_values_v2', to='core.portfolio')),
            ],
            options={
                'ordering': ['date'],
                'indexes': [models.Index(fields=['portfolio', 'date'], name='core_portfo_portfol_b0e6cf_idx')],
                'unique_together': {('portfolio', 'date')},
            },
        ),
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('type', models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('BUY', 'Buy'), ('SELL', 'Sell'), ('DIVIDEND', 'Dividend')], max_length=10)),
                ('ticker', models.CharField(blank=True, max_length=10, null=True)),
                ('shares', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('commission', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('source_id', models.IntegerField(blank=True, null=True)),
                ('source_type', models.CharField(blank=True, choices=[('trade', 'Trade'), ('cash_transaction', 'Cash Transaction'), ('dividend', 'Dividend')], max_length=20, null=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_logs', to='core.portfolio')),
            ],
            options={
                'ordering': ['date'],
                'indexes': [models.Index(fields=['portfolio', 'date'], name='core_transa_portfol_4f2cde_idx'), models.Index(fields=['portfolio', 'type'], name='core_transa_portfol_d69211_idx')],
            },
        ),
        migrations.CreateModel(
            name='YearlyPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('return_pct', models.DecimalField(decimal_places=2, max_digits=10)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yearly_performances', to='core.portfolio')),
            ],
            options={
                'ordering': ['-year'],
                'unique_together': {('portfolio', 'year')},
            },
        ),
        migrations.CreateModel(
            name='YearlyTickerPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('year', models.IntegerField()),
                ('price_return', models.DecimalField(decimal_places=2, max_digits=10)),
                ('div_return', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_return', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dividend_cash', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yearly_ticker_performances', to='core.portfolio')),
            ],
            options={
                'ordering': ['ticker', '-year'],
                'indexes': [models.Index(fields=['portfolio', 'ticker', 'year'], name='core_yearly_portfol_a4519b_idx')],
                'unique_together': {('portfolio', 'ticker', 'year')},
            },
        ),
    ]
