# Generated by Django 5.2.8 on 2026-02-16 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_seoreport_post_delete_media_delete_blogpost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FintestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('text', models.TextField(help_text='Question text (Russian)')),
                ('option_a', models.CharField(max_length=500)),
                ('option_b', models.CharField(max_length=500)),
                ('option_c', models.CharField(blank=True, default='', max_length=500)),
                ('option_d', models.CharField(blank=True, default='', max_length=500)),
                ('option_e', models.CharField(blank=True, default='', max_length=500)),
                ('correct_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1)),
                ('explanation', models.TextField(help_text='Explanation shown in results')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Fintest Question',
                'verbose_name_plural': 'Fintest Questions',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FintestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('age_group', models.CharField(choices=[('<18', 'До 18'), ('18-25', '18-25'), ('26-35', '26-35'), ('36-45', '36-45'), ('46+', '46+')], max_length=10)),
                ('experience', models.CharField(choices=[('0-2', '0-2 года'), ('3-4', '3-4 года'), ('5+', '5+ лет')], max_length=10)),
                ('total_questions', models.PositiveIntegerField()),
                ('total_correct', models.PositiveIntegerField()),
                ('answers_json', models.JSONField(help_text='Per-question detail: [{question_id, selected, correct, is_correct}]')),
            ],
            options={
                'verbose_name': 'Fintest Result',
                'verbose_name_plural': 'Fintest Results',
                'ordering': ['-created_at'],
            },
        ),
    ]
