# Generated by Django 5.2.8 on 2026-02-16 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_fintestquestion_fintestresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='fintestresult',
            name='is_repeat_user',
            field=models.BooleanField(default=False, help_text='User has taken test before (cookie-based)'),
        ),
    ]
