# Generated by Django 5.2.8 on 2026-02-16 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_fintestresult_is_repeat_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='fintestquestion',
            name='edition',
            field=models.CharField(default='v1', help_text='Quiz version', max_length=10),
        ),
        migrations.AddField(
            model_name='fintestresult',
            name='edition',
            field=models.CharField(default='v1', max_length=10),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='fintest_active_edition',
            field=models.CharField(default='v1', help_text="Current active version of the quiz (e.g., 'v1', 'v2')", max_length=10),
        ),
    ]
